apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: phonebook-monitor
  namespace: phonebook
  labels:
    app: phonebook
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      app: phonebook
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - phonebook