apiVersion: v1
kind: ConfigMap
metadata:
  name: phonebook-config
  namespace: phonebook
  labels:
    app: phonebook
data:
  application.yml: |
    server:
      port: 8080
      servlet:
        context-path: /
        encoding:
          charset: UTF-8
          enabled: true
          force: true
    
    spring:
      application:
        name: phonebook
      datasource:
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          maximum-pool-size: 20
          minimum-idle: 5
          connection-timeout: 30000
          idle-timeout: 600000
          max-lifetime: 1800000
      
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            format_sql: true
        open-in-view: false
      
      web:
        resources:
          static-locations: classpath:/static/
          cache:
            period: 3600
    
    logging:
      level:
        com.example.phonebook: INFO
        org.springframework.web: INFO
        org.hibernate.SQL: WARN
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics
      endpoint:
        health:
          show-details: when-authorized