apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: phonebook-pdb
  namespace: phonebook
  labels:
    app: phonebook
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: phonebook